sudo: required
services:
    - docker

before_install: 
  - docker build -t binayverma/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run binayverma/react-test npm test -- --coverage

after_success: 
  - docker build -t binayverma/multi-client ./client
  - docker build -t binayverma/multi-nginx ./nginx
  - docker build -t binayverma/multi-server ./server
  - docker build -t binayverma/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push binayverma/multi-client
  - docker push binayverma/multi-nginx
  - docker push binayverma/multi-server
  - docker push binayverma/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-560780739763
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY